### ISSUE TITLE
Browser not showing screen after connecting

### ISSUE THREAD

**Issue by TheRealRWJ** [pavlobu/deskreen#104]
## Prerequisites

- [?] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/pavlobu/deskreen/tree/master)
- [?] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [?] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`
Not sure what yarn or devtools is. I am NOT a developer
## Expected Behavior

SHowing screen as requested

## Current Behavior
Not showing requested screen

Proberbly browser issue

I am using my first generation iPad Mini iOS 9.3.5  ( Max OS)
Safari v9
## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- Deskreen version or branch : 1.0.5
- Operating System and version :  iOS 9.3.5
- Link to your project :
iPad Mini iOS 9.3.5  ( Max OS)
Safari v9

**Comment by pavlobu** [comment]
Read faq please:
https://deskreen.com/#faq-8
