### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by MarkMa1990** [pavlobu/deskreen#107]
Hi developers, 

I found the soft has high cpu usage, is it possible to reduce that? Thanks.

![image](https://user-images.githubusercontent.com/10673026/107626401-03b74480-6c5e-11eb-848a-e6f54bc477e6.png)

Best regards,
Mark

**Comment by pavlobu** [comment]
Duplicate https://github.com/pavlobu/deskreen/issues/31
