### ISSUE TITLE
Provide API of address

### ISSUE THREAD

**Issue by session250** [pavlobu/deskreen#116]
hi,I must type the address in browser address bar manually when I use two computers.It's not convenient.Can you Provide an API,My webpage can be configured with the server address and the link address can be obtaineds, and the client only needs to open my webpage to get the  link address.Thank you!

**Comment by pavlobu** [comment]
Im not sure what you mean for api, but in future versions I will add trusted devices feature.
With that you will need to type address only one time
https://github.com/pavlobu/deskreen/discussions/71#discussioncomment-321753

**Comment by pavlobu** [comment]
6 digits at the end of adress is for security and they are kind of password, so i will not change that
