### ISSUE TITLE
Not all open windows/apps (Win 10) available in the share App Window option

### ISSUE THREAD

**Issue by justinkelly** [pavlobu/deskreen#17]
Firstly great work on this app - and thanks for open sourcing it!!!!!!!!

It seems that in the share App Window option (Win 10 host) that there is either 
* a limit of 10 windows to choose from
* or not all open apps/windows are available to select

I am attempting to share a specific app window but it is not available in the list
- only 10 windows are shown as selectable - and I have more than 10 open

Cheers

Justin

**Comment by pavlobu** [comment]
Hi Justin,

Thank you for using Deskreen!

Indeed there are some bugs related to that feature a the moment.
I'd recommend trying to be a bit patient and click that Refresh orange button in a select window (next to x close dialog button)
I'll make sure it will be fixed real soon.

Cheers,
Paul

**Comment by justinkelly** [comment]
Thanks Paul - I'll test again in the next update
- the refresh button didn't do anything in my testing

Does the app on windows auto update?

**Comment by pavlobu** [comment]
No it does not autoupdate yet. Autoupdates require code signing and now I'm in a process of gathering funds and knowledge from community to do code signing.

I have implemented feature that will notify you if there is a new version available with os notification. Also you may check in settings pannel there will be a green banner on top of it notifiying that new version is available.

Cheers,
Paul

**Comment by justinkelly** [comment]
thanks @pavlobu for the update - keep up the great work - looking forward to updates in the app

**Comment by pavlobu** [comment]
hi, I made new release with updated chromium engine version for electron.
https://github.com/pavlobu/deskreen/releases/tag/v1.0.2
I've tested it on my windows virtual machine and it worked well
if it does fix your problem, pls share here,

Cheers,
Paul

**Comment by pavlobu** [comment]
closing due to no response
