### ISSUE TITLE
Deskscreen not responding

### ISSUE THREAD

**Issue by code123841** [pavlobu/deskreen#179]
hey? Im using linux ubuntu for some reason every time i click on the allow button once my second screen was requested, nothing happens the whole screen freezes.. Have any idea why this happens?

**Comment by vassdoki** [comment]
I have the same problem. I would use the 3rd screen created with vdl, but no luck. The screen selection does not show up after the connection is established.

**Comment by vassdoki** [comment]
This worked for me: https://github.com/pavlobu/deskreen/issues/166

**Comment by code123841** [comment]
alright
