### ISSUE TITLE
Supported/recommended Display Dummy Plugs?

### ISSUE THREAD

**Issue by Pablohn26** [pavlobu/deskreen#20]
Could you recommend some Display Dummy Plugs? I do not know exactly which kind of device deskreen needs, [for example is this one good](https://es.aliexpress.com/item/4000203277708.html)?

A list with examples and referral links would be good for the project

**Comment by pavlobu** [comment]
the one you mentioned should work,

thank you for using Deskreen

**Comment by pavlobu** [comment]
Links to supported Video Display Adapters is added to [deskreen.com](https://deskreen.com)
