### ISSUE TITLE
Change which window is currently being shared.

### ISSUE THREAD

**Issue by Abban-Fahim** [pavlobu/deskreen#200]
Hey guys, this is a really awesome project and super useful. 

However I cant seem to change which window on my PC is being (for the lack of better words) cast/shared to my other device. The interface for managing connected devices only lets me disconnect the devices I have connected.

Is this not a feature yet, or am I supposed to (meticulously) disconnect my device and re-scan the QR code everytime I want to change the window being shared, OR am I missing something entirely?

Thanks in advance!

**Comment by EDIflyer** [comment]
Yes, at present the only option is to disconnect and re-do the connect process from the beginning.
