### ISSUE TITLE
Blank page on iPad 1 and iPad 2

### ISSUE THREAD

**Issue by luckyshot** [pavlobu/deskreen#21]
Device: iPad 2 (iOS 9.2.1), iPad 1 (iOS 5.1.1)
Browser: Safari

When accessing the client URL (http://xx.xx.xx.xx:3131/123456) it shows a blank page and can't connect.

Not sure if this is a quick fix or a major overhaul of the code, they're pretty old so don't feel too bad about it 😊  
It would be so nice to use Deskreen in these bricks and bring them back to life!

Great work BTW

**Comment by pavlobu** [comment]
Hi the Ipad may be too old to run a web browser with WebRTC
