### ISSUE TITLE
Android/iPadOS compatibility

### ISSUE THREAD

**Issue by musm** [pavlobu/deskreen#23]
Would be great if we could use our Android/iPads as external screens via deskreen.

**Comment by justinkelly** [comment]
as far as im aware that is currently available - and one of the main features of deskreen
- you need the hdmi dongle thing to make the work as a separate screen (rather than a mirror)

have tested win10 to iphone

**Comment by pavlobu** [comment]
it already supports that

cheers
Paul

**Comment by musm** [comment]
Sorry my bad I had some connection issues which I wrongly thought might be related to cross OS, which is clearly wrong since this just operates over IP.
