### ISSUE TITLE
Can only one device be connected？

### ISSUE THREAD

**Issue by aofong** [pavlobu/deskreen#25]
Only one device can be connected, an error will be reported when the second device is connected.

```
You were not allowed to connect.
You may close this browser window then try to connect again.
```

![image](https://user-images.githubusercontent.com/3070161/105154439-8445c200-5b44-11eb-9ba2-c7f50d7be1e5.png)

**Comment by pavlobu** [comment]
you can connect as many as you want, just make sure you are always using newly generated address under QR code with NEW last 6 digits for new device to be connected.

When one device is already using a link no other devices can use it anymore. the new link is generated when you click "Connect New Device"

Cheers
Paul

**Comment by jarrard** [comment]
Not my experience. The link is connected to the browser window, once that is closed, the devices connection is invalidated. Poor programming!

**Comment by jarrard** [comment]
Yeah means you must constantly keep the phone active (touching screen) and also keep TV window open... Rather unfortunate limitation.

**Comment by YeXin451664** [comment]
yarn dev-- 在开发模式下运行为啥会控制台会报错运行不起来呢
