### ISSUE TITLE
Is the Project Dead ?

### ISSUE THREAD

**Issue by adamency** [pavlobu/deskreen#253]
No commit on the project has been made since november 2022, i.e. almost 1 and a half years now. @pavlobu did you abandon the project ? Should we create a community-driven fork in order to continue working on the software ?

There is no worries if you can't work on it anymore, but it would be good to have this information explicitly stated so that the community can start making work on another project so that the Deskcreen software still live on :).

**Comment by pavlobu** [comment]
I want you to know that your significant PRs are welcome.

By significant I mean not one-line code changes or fixes in readme files.

I've seen only a few community contributions so far. Financial and code contributions are so small compared to how much personal time I've invested in this project, so it is hard to keep me motivated to develop this project actively.

Things may change in the future if I see more contributions.

**Comment by adamency** [comment]
I understand, thanks for answering :).

**Comment by KaKi87** [comment]
Okay, accepting PRs is one thing, but what about responding to bug reports and feature requests ? Are you indefinitely stopping doing it ? Thanks
