### ISSUE TITLE
Allow port-forwarding services to be used such as ngrok

### ISSUE THREAD

**Issue by jonot-cyber** [pavlobu/deskreen#35]
Hello. Due to various reasons, I cannot connect my phone and my PC to the same wifi. By using services such as ngrok, I hoped I would be able to connect, and use the app. However, it gave a "something went wrong" message. Please add support for these services. Thank you!

**Comment by pavlobu** [comment]
Hi thanks for submitting this issue. 

This is a very specific request. We will be thinking on how to bypass these limitations but not seeing fixing it in near future.

If you happen to know the solution and you have a code, you can PR it to this git repo.

Cheers,
Paul

**Comment by pavlobu** [comment]
I'm also having network issues when I'm connected to NordVPN. I think VPN settings can be adjusted to allow access to private networks and not Deskreen code should be changed for that.

**Comment by pavlobu** [comment]
I can confirm that vpn can be set to allow private network access. NordVPN has this optikn at least in settings and deskreen works with it. So it is a problem of your config of system with working with ngrok, you need to find a way to bypass that limitation of ngrok yourself. If you happen to find a solution, pls write it here it may help others with similar issue.

Cheers,
Paul
