### ISSUE TITLE
FYI: Linux on Xorg can create virtual desktops

### ISSUE THREAD

**Issue by Kwbmm** [pavlobu/deskreen#36]
I saw on the readme that you are looking for a way to get rid of the dummy plug. Well, if you're running any linux distro with Xorg X11 display server, then you can simply:

```sh
remoteHScreen=2560
remoteVScreen=1600
refreshRate=60
existingScreenName="DP1"

params=$(gtf ${remoteHScreen} ${remoteVScreen} ${refreshRate} | grep Modeline | sed 's/^\s\sModeline \".*\"\s*//g')

xrandr --newmode "extraScreen" ${params}
xrandr --addmode VIRTUAL1 extraScreen
xrandr --output VIRTUAL1 --left-of ${existingScreenName} --mode extraScreen
```

And to delete the screen:
```sh
xrandr --output VIRTUAL1 --off
xrandr --delmode VIRTUAL1 
xrandr --rmmode extraScreen
```

I believe this can be done on Wayland as well, but since I don't use wayland, I dont' really know...

Regarding the other 2 OSes:
  - **OSX:** Although similar to linux in many ways, OSX has long departed from X11 display server. I have investigated quite a lot on how to create a virtual monitor through the command line, but I could find anything for the display server used by Mac OS.
    *I suspect that installing XQuartz might allow you to do this, but I'm not even sure if XQuartz is still working on newer version of OSX*
  - **Windows:** I don't believe there's anything working out of the box. Did some research, couldn't find anything. Likely needs an ad-hoc solution.

**Comment by Kwbmm** [comment]
Sorry I figured this may be a better fit for "Discussions" section. Feel free to close and move it there.

**Comment by pavlobu** [comment]
Hey thank you for sharing your useful knowledge here!

Sure I have opened a discussion on this topic [here](https://github.com/pavlobu/deskreen/discussions/37#discussion-2016522)

**Comment by callegar** [comment]
Applications to not appear to see the virtual screen that is attached in this way. For instance libreoffice does not seem to propose this screen to have presentation and presenter console in different screens.  Any clue?
