### ISSUE TITLE
Build / instruction issue

### ISSUE THREAD

**Issue by pinusc** [pavlobu/deskreen#39]
On Arch Linux, while trying to run the package from source, I get the following error when running `yarn start`:
```
yarn run v1.22.10
$ yarn build
$ yarn build-client && yarn build-main && yarn build-renderer
$ cd app/client && cross-env SKIP_PREFLIGHT_CHECK=true yarn build
$ react-scripts build
/bin/sh: line 1: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like the relevant line is `/bin/sh: line 1: react-scripts: command not found`.  It looks like `react-scripts` is a dependency in `app/client/package.json`. 

This can be fixed with `cd app/client; yarn install`, then going back to project root and running `yarn start`.

I don't know yarn, and I'm not sure if it can handle running `yarn install` in `app/client` on its own; if so, it should be configured to do it. Otherwise, there should be instructions in the README specifying that it is necessary to run `yarn install` in `app/client` as well.

**Comment by pavlobu** [comment]
Great find, yes docs can be improved, you can contribute on README.md if you want, so that the others will not bump into this issue anymore. Otherwise I'll do it a bit later, while handling other stuff I have to do at the moment.

Cheers,
Paul
