### ISSUE TITLE
Allow sharing application on different desktops

### ISSUE THREAD

**Issue by NIXOYE** [pavlobu/deskreen#40]
All OS' have the option to have multiple "Desktops", it would be very useful to be able to share an application thats on a Desktop your not currently on. (for example on windows you can press the windows key + TAB to open more desktops and windows key + ctrl + arrow keys to change between desktops)

**Comment by pavlobu** [comment]
Hi I was really wanting to implement that feature but technology is not there yet for electronjs. Electro simply records a physical desktop not an emulated one which are "virtual desktops feature" in Windows, Mac and Linux.

If this would work, I would not have to ask for community help to write display drivers to fix this problem.

So I'll close this issue for now. Who knows, maybe electron will support that feature in future and we will definitely benefit from It.

Cheers,
Paul
