### ISSUE TITLE
Is this tool supposed to work with PC's, that are connected via cable?

### ISSUE THREAD

**Issue by KpauMupa** [pavlobu/deskreen#46]
## TODO

write question template
I have a PC that is connected to the router via cable, and the router is giving away WI-FI. Should this tool work in that case and connect my smartphone, which is connected to wifi, to PC?

**Comment by pavlobu** [comment]
Yes it works that way

**Comment by KpauMupa** [comment]
> 
> 
> Yes it works that way

But i can't make it work...

**Comment by pavlobu** [comment]
You have a forewall, and/antivirus enabled, also if on windows you shoild allow local private network access to deskreen

**Comment by KpauMupa** [comment]
> 
> 
> You have a firewall, and/or antivirus enabled, also if on windows you should allow local private network access to deskreen

Oh, sorry for wasting your time! I forgot that my firewall thinks that im connected to public network and uses public network settings!
