### ISSUE TITLE
Add a portable version for Windows

### ISSUE THREAD

**Issue by Bellisario** [pavlobu/deskreen#51]
Actually, there isn't a Windows portable version, yet.

Please, add a portable version: I'd like to test the app features but without installing it.

**Comment by pavlobu** [comment]
copy that, do you happen to know how to do it with electron ?

**Comment by Bellisario** [comment]
Yes @pavlobu, you can do a portable version with electron-builder... please read [this article](https://stackoverflow.com/questions/50905886/i-am-trying-to-turn-my-electron-app-to-windows-portable).
Good job!

**Comment by pavlobu** [comment]
done! download here:
https://github.com/pavlobu/deskreen/releases/tag/v1.0.3
