### ISSUE TITLE
Application Window sharing - limited list

### ISSUE THREAD

**Issue by geoynomous** [pavlobu/deskreen#56]
The list seems to show only some of all active applications windows - like 12 or 16 (can't check right now). When I add a new browser window for instance, it does not show up .. even after reload button press.

**Comment by pavlobu** [comment]
ok it is a known bug, you can submit a PR if you have a solution

**Comment by pavlobu** [comment]
hi, I made new release with updated chromium engine version for electron.
https://github.com/pavlobu/deskreen/releases/tag/v1.0.2
I've tested it on my windows virtual machine and it worked well with app windows list
if it does fix your problem, pls share here,

Cheers,
Paul

**Comment by pavlobu** [comment]
Closing due to no response
