### ISSUE TITLE
Change Allow button to green or blue

### ISSUE THREAD

**Issue by aha999** [pavlobu/deskreen#61]
Alow button is usually associated with blue / green color, so i think you should change the color of the Allow button.

![slika](https://user-images.githubusercontent.com/50620416/105888304-19e1c580-600d-11eb-936b-a46fd9d7ba00.png)

**Comment by pavlobu** [comment]
Hi,
wrong action on this step is dangerous, so I made it red.
If you are a professional app UI designer, you can share your portfolio here and we can discuss on improving a UI of Deskreen

**Comment by pavlobu** [comment]
Closing due to no response
