### ISSUE TITLE
Display driver for macOS

### ISSUE THREAD

**Issue by lhaeger** [pavlobu/deskreen#63]
Regarding a display driver for macOS, this may be a starting point: https://github.com/icedman/EWProxyFramebuffer 

Some details can be found at https://www.tonymacx86.com/threads/share-virtual-display-like-sidecar-on-mojave.285494/

**Comment by pavlobu** [comment]
Hi, thanks please share it here:
https://github.com/pavlobu/deskreen/discussions/37
