### ISSUE TITLE
Second screen not offered to share

### ISSUE THREAD

**Issue by Rokory** [pavlobu/deskreen#69]
## Expected Behavior

Both screens should be offered to share.

## Current Behavior

Only the bigger primary screen is offered to be shared.

## Steps to Reproduce

In the Select step, only the primary screen is offered to share

## Context

I wanted to use an iPad as secondary screen. The secondary screen is cable connected and shows up in display settings of Windows. Windows is set to extend the Desktop to the secondary screen.

## Your Environment

Windows 10 20H2
Deskreen 1.0.2 Binary
Primary screen 5120 x 1440
Secondary screen 2048 x 1536

**Comment by pavlobu** [comment]
Hey, did you try hitting orange a refresh buttion couple of times after few seconds when you connected your screen.

This may be an electron bug, coz other users did not report thos issue on windows yet.

Cheers,
Paul

**Comment by Rokory** [comment]
Yes, the screen was connected long before I even started Deskreen. Additional info: One screen is connected using Displayport, the other using HDMI. Maybe this is an issue.

**Comment by pavlobu** [comment]
Did restarting the app help? It may be related to bug with electron

**Comment by Rokory** [comment]
Negative. Restarting app and computer does not help. I also tried with different resolutions and more common ones (e. g. 1080p) with no effect.

**Comment by pavlobu** [comment]
that must be the bug in electron :/ can you try lower version of deskreen 1.0.0?

I have updated chromium engine in 1.0.2

**Comment by Rokory** [comment]
I think, I have found the problem. It is indeed an Electron problem. It seems connected with the copy protection of HDMI 2.0. My graphics adapter and my screen both support this protocol. However, debugging the source code, I found, that Electron does not offer this particular screen. When attaching a display dummy adapter instead, which does not support HDMI 2.0, Deskreen offers the second screen.

**Comment by pavlobu** [comment]
Thanks for good details on that. Closing due to it is not an app problem itself. It is an electron bug. Maybe it will be fixed when I update electron to even newer version with newer chromium, right now its latest
