### ISSUE TITLE
Can't select windows or screen on Windows 10

### ISSUE THREAD

**Issue by cagnulein** [pavlobu/deskreen#74]
## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date [`master` branch](https://github.com/pavlobu/deskreen/tree/master)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Select windows or screen

## Current Behavior

I can't select it, i click on it but nothing happens :(

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/48216/106263166-50455d80-6224-11eb-9dc7-63a9638ebff4.png)

- Deskreen version or branch : 1.0.2
- Operating System and version : Windows 10 LTSC

**Comment by pavlobu** [comment]
Sorry to see it happening. You can try newer version 1.0.3 maybe it will help. I can t guarantee it will run ok on every pc in the world, sorry

**Comment by cagnulein** [comment]
yeah it works, but it hangs after that view. No problem man, i will buy a real monitor :D
