### ISSUE TITLE
不能读取软件窗口或只能读取一两个

### ISSUE THREAD

**Issue by Git0503** [pavlobu/deskreen#75]
![image](https://user-images.githubusercontent.com/49622794/106282625-d2ad3c00-627b-11eb-8b28-a496e920728a.png)

**Comment by pavlobu** [comment]
No details provided. Like app version, windows version. So I close this issue

**Comment by Git0503** [comment]
app version：1.0.3


windows version：Windows10


截图：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pavlobu/deskreen"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上9:51
收件人:&nbsp;"pavlobu/deskreen"<deskreen@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pavlobu/deskreen] 不能读取软件窗口或只能读取一两个 (#75)





 
No details provided. Like app version, windows version. So I close this issue
