### ISSUE TITLE
Auto scan

### ISSUE THREAD

**Issue by imneonizer** [pavlobu/deskreen#79]
Give a common ip address for all remote devices to visit and let the user select id, instead of entering it as part of url this way reconnection will be effortless even if server has created a new id.

**Comment by pavlobu** [comment]
# Here you post only concrete examples of enhancements with code and solutions that you have. Other BIG enhancements and general ideas of features you would like to see in Deskreen, you post here: https://github.com/pavlobu/deskreen/discussions/50

## Thanks

closing this issue
