### ISSUE TITLE
Can not create connection with Deskreen by WebView on Android

### ISSUE THREAD

**Issue by softwind9** [pavlobu/deskreen#84]
I am trying to open Deskreen url in an Android Webview. 

But I got this message :

I/chromium: [INFO:CONSOLE(2)] "TypeError: Object.values is not a function", source: http://192.168.199.137:3131/static/js/2.5f2b9264.chunk.js (2)

BTW: It's working well with chrome on Android. 

Would you please give me some advice to make it work with Android Webview?

**Comment by pavlobu** [comment]
Hi sorry, this is a create-react-app based client code. If create-react-app boilerplate does not work, then Deskreen will not work in Android WebView. Besides it needs a support for webrtc, if Android WebView does not have it, then it will not work. Just use a Chrome or Firefox browsers for android and it works well.

Closing this issue coz it is an edge case that is not Deskreen's fault.
