### ISSUE TITLE
Binary is not signed

### ISSUE THREAD

**Issue by tobi** [pavlobu/deskreen#94]
You are probably aware of this, but the OSX image isn't signed and so raises a warning. 

![Screen Shot 2021-02-02 at 4 44 06 PM](https://user-images.githubusercontent.com/347/106660091-f7542d00-6575-11eb-94c4-e60446d115fe.png)

**Comment by pavlobu** [comment]
Yes I'm aware of this

**Comment by pavlobu** [comment]
App will be code signed, stay tuned.

**Comment by bryanparadis** [comment]
Looks to still not be code signed. Any update on this? Thanks
