### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:3131

### ISSUE THREAD

**Issue by rafklu** [pavlobu/deskreen#97]
**Platform**: Windows 10
**App Version**: 1.0.4

There is no difference if application started with admin privileges or without. Error is popping up on startup.

### Error Message
![error-message](https://user-images.githubusercontent.com/3036563/106936850-5ef8ac80-671d-11eb-9776-b80593e76e06.png)

**Comment by pavlobu** [comment]
restart app, then try
restart a computer, then try
?

**Comment by pavlobu** [comment]
[http://deskreen.com/#faq-4](http://deskreen.com/#faq-4)
