### ISSUE TITLE
无法正常下载，下载只有几kb每秒，下载一部分就会网络出错，点击重试会提示权限错误

### ISSUE THREAD

**Issue by yhongm** [pavlobu/deskreen#99]
## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date [`master` branch](https://github.com/pavlobu/deskreen/tree/master)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- Deskreen version or branch :
- Operating System and version :
- Link to your project :

**Comment by pavlobu** [comment]
Hi, try to use motrix.app fro download
https://github.com/agalwood/Motrix
